#pragma once

#ifndef THRUST_DEVICE_SYSTEM
#  if _OPENMP
#    define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_OMP
#  else
#    define THRUST_DEVICE_SYSTEM THRUST_DEVICE_SYSTEM_CPP
#  endif
#endif // THRUST_DEVICE_SYSTEM

